package com.zclei.boxingfitness

import com.zclei.boxingfitness.model.AppLanguage

object UiStrings {
    fun get(language: AppLanguage, key: String): String =
        translations(language)[key] ?: ENGLISH[key] ?: key

    private fun translations(language: AppLanguage): Map<String, String> =
        when (language) {
            AppLanguage.Chinese -> CHINESE
            AppLanguage.English -> ENGLISH
            AppLanguage.French -> FRENCH
            AppLanguage.Thai -> THAI
        }

    private val CHINESE =
        mapOf(
            "settings_subtitle" to "语言和灵敏度会保存在当前设备，下次打开 APP 时自动生效。",
            "language_helper" to "界面和训练提示会按照这里的语言显示。",
            "language_chinese" to "简体中文",
            "language_english" to "英语",
            "language_french" to "法语",
            "language_thai" to "泰语",
            "sensitivity_stable" to "高手",
            "sensitivity_balanced" to "标准",
            "sensitivity_sensitive" to "新手",
            "restore_default" to "恢复默认",
            "activation_success_ready" to "激活成功，本机已完成验证，现在可以开始训练。",
            "activation_verified_status" to "设备已验证，可直接开始训练。",
            "activation_ready_title" to "设备已验证",
            "activation_ready_subtitle" to "当前设备已经通过认证，可以直接开始训练，也可以继续调整设置。",
            "activation_serial_label" to "序列号",
            "activation_status_label" to "状态",
            "activation_status_verified" to "已验证",
            "activation_last_check_label" to "最近校验",
            "activation_just_now" to "刚刚",
            "title" to "BoxingFitness",
            "subtitle" to "橙金响应视觉与实时计数结合，带来更沉浸的拳击反应训练体验。",
            "mode" to "模式",
        "page_training_center" to "锻炼中心",
            "page_training_achievements" to "训练成就",
            "page_leaderboard" to "榜单排名",
            "page_profile" to "个人中心",
            "latest_report" to "最新报告",
            "no_report" to "暂无训练报告。",
            "start" to "开始",
            "stop" to "停止",
            "settings" to "设置",
            "permission_required" to "需要蓝牙设备权限。",
            "ready" to "准备开始训练。",
            "keep_quiet" to "请保持安静。",
            "analyzing_mic" to "正在分析手机蓝牙设备...",
            "adapting_noise" to "正在适配当前环境噪声...",
            "calibrating_keep_quiet" to "正在校正背景声音，请保持安静。",
            "calibration_fail_unstable" to "环境噪声波动过大，校正不合格，请在安静环境下重试。",
            "calibration_fail_retry" to "稳定背景样本不足，请保持安静后重新校正。",
            "training_complete" to "训练完成。",
            "training_stopped" to "训练已停止。",
            "training_live" to "正在训练",
            "training_failed" to "训练失败。",
            "prepare_short" to "安静",
            "calibration_short" to "校正",
            "done_short" to "完成",
            "error_short" to "错误",
            "retry_short" to "重试",
            "retry_calibration" to "重新校正",
            "save" to "保存",
            "cancel" to "取消",
            "language" to "APP 语言",
            "sensitivity" to "灵敏度",
            "sensitivity_helper" to "范围 0-100，数字越大，灵敏度越高。",
            "total_hits" to "总击打次数",
            "average_frequency" to "平均频率",
            "hits_per_second" to "次/秒",
            "best_burst" to "最佳连续 3 秒",
            "burst_start" to "爆发起点",
            "hits" to "次",
            "activation_title" to "设备激活",
            "activation_subtitle" to "请输入包装盒内的 11 位序列号和 8 位激活码。",
            "activation_hint" to "完成激活后，才可以开始训练。",
            "activation_required" to "当前 APP 尚未激活。",
            "activation_loading" to "正在验证序列号和激活码...",
            "activation_success" to "激活成功，现在可以开始使用。",
            "activation_failed" to "激活失败，请稍后重试。",
            "activation_serial_not_found" to "账号数据暂不可用，请稍后重试。",
            "activation_invalid_code" to "激活码错误，请重新输入。",
            "activation_already_bound" to "该序列号已在另一台设备激活。",
            "activation_not_activated" to "当前设备尚未完成激活。",
            "activation_network_error" to "无法连接认证服务，请检查网络后重试。",
            "serial_hint" to "请输入 11 位序列号",
            "code_hint" to "请输入 8 位激活码",
            "serial_invalid" to "请输入正确的 11 位序列号。",
            "code_invalid" to "请输入正确的 8 位激活码。",
            "activate" to "立即激活",
            "lock_short" to "激活",
            "profile_title" to "个人中心",
            "profile_edit" to "编辑资料",
            "profile_avatar" to "个人头像",
            "profile_nickname" to "昵称",
            "profile_country" to "地区代码",
            "profile_language" to "语言",
            "profile_saved" to "个人资料已更新。",
            "profile_save_failed" to "资料保存失败，请检查后重试。",
            "profile_empty" to "云端资料暂未准备好。",
            "cloud_refresh" to "刷新云端",
            "cloud_sync_loading" to "正在同步云端数据...",
            "cloud_sync_ready" to "云端数据已同步。",
            "cloud_sync_network" to "当前无法连接云端服务。",
            "cloud_sync_idle" to "等待下一次云端同步。",
            "history_title" to "训练记录",
            "no_history" to "暂无训练记录。",
            "leaderboard_title" to "榜单排名",
            "leaderboard_refresh" to "刷新榜单",
            "leaderboard_loading" to "正在加载榜单...",
            "leaderboard_ready" to "榜单已更新。",
            "leaderboard_empty" to "暂无榜单数据。",
            "leaderboard_me" to "我的排名",
            "leaderboard_no_rank" to "当前尚未上榜。",
            "total_sessions" to "总训练次数",
            "best_30_hits" to "30 秒最佳成绩",
            "best_60_hits" to "60 秒最佳成绩",
            "cd_avatar_swatch" to "头像颜色 %d",
        )

    private val ENGLISH =
        mapOf(
            "settings_subtitle" to "Language and sensitivity are saved on this device and applied automatically next time.",
            "language_helper" to "UI text and training prompts follow this language setting.",
            "language_chinese" to "Simplified Chinese",
            "language_english" to "English",
            "language_french" to "French",
            "language_thai" to "Thai",
            "sensitivity_stable" to "Stable",
            "sensitivity_balanced" to "Balanced",
            "sensitivity_sensitive" to "Sensitive",
            "sensitivity_stable_desc" to "More conservative and better at reducing false counts in noisy places.",
            "sensitivity_balanced_desc" to "Recommended default for everyday training.",
            "sensitivity_sensitive_desc" to "Easier to detect light hits, but also more reactive to background sound.",
            "restore_default" to "Restore Default",
            "activation_success_ready" to "Activation complete. This device is verified and ready to train.",
            "activation_verified_status" to "This device is verified and ready.",
            "activation_ready_title" to "Device Verified",
            "activation_ready_subtitle" to "This device has already been activated. You can start training right away or fine-tune settings below.",
            "activation_serial_label" to "Serial",
            "activation_status_label" to "Status",
            "activation_status_verified" to "Verified",
            "activation_last_check_label" to "Last check",
            "activation_just_now" to "Just now",
            "title" to "BoxingFitness",
            "subtitle" to "Premium orange-gold visuals meet real-time punch counting for a more immersive reflex workout.",
            "mode" to "Mode",
            "page_training_center" to "Training",
            "page_training_achievements" to "Achievements",
            "page_leaderboard" to "Leaderboard",
            "page_profile" to "Profile",
            "latest_report" to "Latest Report",
            "no_report" to "No training session yet.",
            "start" to "Start",
            "stop" to "Stop",
            "settings" to "Settings",
            "permission_required" to "Bluetooth connection is required.",
            "ready" to "Ready to train.",
            "keep_quiet" to "Please keep quiet.",
            "analyzing_mic" to "Analyzing this phone mic...",
            "adapting_noise" to "Adapting to current phone noise...",
            "calibrating_keep_quiet" to "Calibrating background sound. Please keep quiet.",
            "calibration_fail_unstable" to "Noise changed too much during calibration. Please retry in a quieter environment.",
            "calibration_fail_retry" to "Not enough stable background sound was collected. Please retry.",
            "training_complete" to "Training complete.",
            "training_stopped" to "Training stopped.",
            "training_live" to "Training live",
            "training_failed" to "Training failed.",
            "prepare_short" to "QUIET",
            "calibration_short" to "CAL",
            "done_short" to "DONE",
            "error_short" to "ERR",
            "retry_short" to "RETRY",
            "retry_calibration" to "Retry Calibration",
            "save" to "Save",
            "cancel" to "Cancel",
            "language" to "App Language",
            "sensitivity" to "Sensitivity",
            "sensitivity_helper" to "Range 0-100, default 50. Higher values mean higher sensitivity.",
            "total_hits" to "Total hits",
            "average_frequency" to "Average frequency",
            "hits_per_second" to "hits/s",
            "best_burst" to "Best 3-second burst",
            "burst_start" to "Burst start",
            "hits" to "hits",
            "activation_title" to "Device Activation",
            "activation_subtitle" to "Enter the 11-digit serial number and 8-digit activation code from the package.",
            "activation_hint" to "Activate this app before starting training.",
            "activation_required" to "This app is not activated yet.",
            "activation_loading" to "Verifying serial number and activation code...",
            "activation_success" to "Activation successful. You can start training now.",
            "activation_failed" to "Activation failed. Please try again.",
            "activation_serial_not_found" to "Account data is unavailable. Please try again later.",
            "activation_invalid_code" to "Activation code is invalid.",
            "activation_already_bound" to "This serial number is already activated on another device.",
            "activation_not_activated" to "This device is not activated.",
            "activation_network_error" to "Unable to reach the activation server. Please check your network.",
            "serial_hint" to "Enter 11-digit serial number",
            "code_hint" to "Enter 8-digit activation code",
            "serial_invalid" to "Please enter a valid 11-digit serial number.",
            "code_invalid" to "Please enter a valid 8-digit activation code.",
            "activate" to "Activate",
            "lock_short" to "LOCK",
            "profile_title" to "Profile",
            "profile_edit" to "Edit Profile",
            "profile_avatar" to "Avatar",
            "profile_nickname" to "Nickname",
            "profile_country" to "Region code",
            "profile_language" to "Language",
            "profile_saved" to "Profile updated.",
            "profile_save_failed" to "Unable to save profile.",
            "profile_empty" to "Cloud profile is not ready yet.",
            "cloud_refresh" to "Refresh Cloud",
            "cloud_sync_loading" to "Syncing cloud data...",
            "cloud_sync_ready" to "Cloud data is up to date.",
            "cloud_sync_network" to "Cloud service is unavailable right now.",
            "cloud_sync_idle" to "Waiting for the next cloud sync.",
            "history_title" to "Training History",
            "no_history" to "No training history yet.",
            "leaderboard_title" to "Leaderboard",
            "leaderboard_refresh" to "Refresh Leaderboard",
            "leaderboard_loading" to "Loading leaderboard...",
            "leaderboard_ready" to "Leaderboard updated.",
            "leaderboard_empty" to "No leaderboard data yet.",
            "leaderboard_me" to "My rank",
            "leaderboard_no_rank" to "You are not ranked yet.",
            "total_sessions" to "Total sessions",
            "best_30_hits" to "Best 30-second score",
            "best_60_hits" to "Best 60-second score",
            "cd_avatar_swatch" to "Avatar color %d",
        )

    private val FRENCH =
        mapOf(
            "settings_subtitle" to "La langue et la sensibilité sont enregistrées sur cet appareil.",
            "language_helper" to "Les textes et invites suivent cette langue.",
            "language_chinese" to "Chinois simplifié",
            "language_english" to "Anglais",
            "language_french" to "Français",
            "language_thai" to "Thaï",
            "sensitivity_stable" to "Stable",
            "sensitivity_balanced" to "Équilibré",
            "sensitivity_sensitive" to "Sensible",
            "sensitivity_stable_desc" to "Réduit mieux les faux comptages dans un environnement bruyant.",
            "sensitivity_balanced_desc" to "Réglage recommandé pour un usage quotidien.",
            "sensitivity_sensitive_desc" to "Détecte plus facilement les frappes légères.",
            "restore_default" to "Réinitialiser",
            "activation_success_ready" to "Activation terminée. Cet appareil est prêt.",
            "activation_verified_status" to "Cet appareil est vérifié.",
            "activation_ready_title" to "Appareil vérifié",
            "activation_ready_subtitle" to "Cet appareil est déjà activé et prêt à s'entraîner.",
            "activation_serial_label" to "Série",
            "activation_status_label" to "État",
            "activation_status_verified" to "Vérifié",
            "activation_last_check_label" to "Dernière vérification",
            "activation_just_now" to "À l'instant",
            "title" to "BoxingFitness",
            "subtitle" to "L'application calibre le bruit de fond puis compte en temps réel.",
            "mode" to "Mode",
            "page_training_center" to "Entraînement",
            "page_training_achievements" to "Succès",
            "page_leaderboard" to "Classement",
            "page_profile" to "Profil",
            "latest_report" to "Dernier rapport",
            "no_report" to "Aucune séance pour le moment.",
            "start" to "Démarrer",
            "stop" to "Arrêter",
            "settings" to "Réglages",
            "permission_required" to "La connexion Bluetooth est requise.",
            "ready" to "Prêt à s'entraîner.",
            "keep_quiet" to "Veuillez rester silencieux.",
            "analyzing_mic" to "Analyse du micro...",
            "adapting_noise" to "Adaptation au bruit actuel...",
            "calibrating_keep_quiet" to "Calibration du bruit de fond en cours.",
            "calibration_fail_unstable" to "Le bruit a trop varié pendant la calibration.",
            "calibration_fail_retry" to "Pas assez d'échantillons stables. Réessayez.",
            "training_complete" to "Entraînement terminé.",
            "training_stopped" to "Entraînement arrêté.",
            "training_live" to "Entraînement en cours",
            "training_failed" to "Échec de l'entraînement.",
            "prepare_short" to "CALME",
            "calibration_short" to "CAL",
            "done_short" to "FIN",
            "error_short" to "ERR",
            "retry_short" to "RETRY",
            "retry_calibration" to "Recalibrer",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "language" to "Langue de l'app",
            "sensitivity" to "Sensibilité",
            "sensitivity_helper" to "Plage 0-100, valeur par défaut 50.",
            "total_hits" to "Frappes totales",
            "average_frequency" to "Fréquence moyenne",
            "hits_per_second" to "coups/s",
            "best_burst" to "Meilleure séquence de 3 s",
            "burst_start" to "Début du burst",
            "hits" to "coups",
            "activation_title" to "Activation de l'appareil",
            "activation_subtitle" to "Entrez le numéro de série à 11 chiffres et le code à 8 chiffres.",
            "activation_hint" to "Activez l'application avant de commencer.",
            "activation_required" to "Cette application n'est pas encore activée.",
            "activation_loading" to "Vérification du numéro de série et du code...",
            "activation_success" to "Activation réussie.",
            "activation_failed" to "Échec de l'activation.",
            "activation_serial_not_found" to "Numéro de série introuvable.",
            "activation_invalid_code" to "Code d'activation invalide.",
            "activation_already_bound" to "Ce numéro de série est déjà activé sur un autre appareil.",
            "activation_not_activated" to "Cet appareil n'est pas activé.",
            "activation_network_error" to "Impossible de joindre le serveur d'activation.",
            "serial_hint" to "Numéro de série (11 chiffres)",
            "code_hint" to "Code d'activation (8 chiffres)",
            "serial_invalid" to "Veuillez saisir un numéro de série valide.",
            "code_invalid" to "Veuillez saisir un code valide.",
            "activate" to "Activer",
            "lock_short" to "LOCK",
            "profile_title" to "Profil",
            "profile_edit" to "Modifier le profil",
            "profile_avatar" to "Avatar",
            "profile_nickname" to "Pseudo",
            "profile_country" to "Code région",
            "profile_language" to "Langue",
            "profile_saved" to "Profil mis à jour.",
            "profile_save_failed" to "Impossible d'enregistrer le profil.",
            "profile_empty" to "Le profil cloud n'est pas prêt.",
            "cloud_refresh" to "Actualiser",
            "cloud_sync_loading" to "Synchronisation cloud...",
            "cloud_sync_ready" to "Données cloud synchronisées.",
            "cloud_sync_network" to "Service cloud indisponible.",
            "cloud_sync_idle" to "En attente de la prochaine synchronisation.",
            "history_title" to "Historique",
            "no_history" to "Aucun historique pour le moment.",
            "leaderboard_title" to "Classement",
            "leaderboard_refresh" to "Actualiser le classement",
            "leaderboard_loading" to "Chargement du classement...",
            "leaderboard_ready" to "Classement mis à jour.",
            "leaderboard_empty" to "Aucune donnée de classement.",
            "leaderboard_me" to "Mon rang",
            "leaderboard_no_rank" to "Vous n'êtes pas encore classé.",
            "total_sessions" to "Séances totales",
            "best_30_hits" to "Meilleur score 30 s",
            "best_60_hits" to "Meilleur score 60 s",
            "cd_avatar_swatch" to "Couleur d'avatar %d",
        )

    private val THAI =
        mapOf(
            "settings_subtitle" to "ภาษาและความไวจะถูกบันทึกไว้ในอุปกรณ์นี้",
            "language_helper" to "ข้อความและคำสั่งฝึกจะใช้ภาษานี้",
            "language_chinese" to "จีนตัวย่อ",
            "language_english" to "อังกฤษ",
            "language_french" to "ฝรั่งเศส",
            "language_thai" to "ไทย",
            "sensitivity_stable" to "นิ่ง",
            "sensitivity_balanced" to "สมดุล",
            "sensitivity_sensitive" to "ไว",
            "sensitivity_stable_desc" to "ลดการนับผิดได้ดีกว่าในที่มีเสียงรบกวน",
            "sensitivity_balanced_desc" to "ค่าแนะนำสำหรับการใช้งานทั่วไป",
            "sensitivity_sensitive_desc" to "ตรวจจับการตีเบาได้ง่ายขึ้น",
            "restore_default" to "คืนค่าเริ่มต้น",
            "activation_success_ready" to "เปิดใช้งานสำเร็จ อุปกรณ์นี้พร้อมใช้งานแล้ว",
            "activation_verified_status" to "อุปกรณ์นี้ได้รับการยืนยันแล้ว",
            "activation_ready_title" to "อุปกรณ์ยืนยันแล้ว",
            "activation_ready_subtitle" to "อุปกรณ์นี้เปิดใช้งานแล้ว และพร้อมเริ่มฝึก",
            "activation_serial_label" to "ซีเรียล",
            "activation_status_label" to "สถานะ",
            "activation_status_verified" to "ยืนยันแล้ว",
            "activation_last_check_label" to "ตรวจสอบล่าสุด",
            "activation_just_now" to "เมื่อสักครู่",
            "title" to "BoxingFitness",
            "subtitle" to "แอปจะปรับเทียบเสียงรบกวนก่อน แล้วนับแบบเรียลไทม์",
            "mode" to "โหมด",
            "page_training_center" to "การฝึก",
            "page_training_achievements" to "ความสำเร็จ",
            "page_leaderboard" to "อันดับ",
            "page_profile" to "โปรไฟล์",
            "latest_report" to "รายงานล่าสุด",
            "no_report" to "ยังไม่มีข้อมูลการฝึก",
            "start" to "เริ่ม",
            "stop" to "หยุด",
            "settings" to "ตั้งค่า",
            "permission_required" to "ต้องอนุญาตไมโครโฟน",
            "ready" to "พร้อมฝึก",
            "keep_quiet" to "กรุณาเงียบ",
            "analyzing_mic" to "กำลังวิเคราะห์ไมโครโฟน...",
            "adapting_noise" to "กำลังปรับให้เข้ากับเสียงรบกวน...",
            "calibrating_keep_quiet" to "กำลังปรับเทียบเสียงพื้นหลัง",
            "calibration_fail_unstable" to "เสียงรบกวนเปลี่ยนมากเกินไป ระหว่างการปรับเทียบ",
            "calibration_fail_retry" to "มีตัวอย่างเสียงที่เสถียรไม่เพียงพอ กรุณาลองใหม่",
            "training_complete" to "ฝึกเสร็จแล้ว",
            "training_stopped" to "หยุดการฝึกแล้ว",
            "training_live" to "กำลังฝึก",
            "training_failed" to "การฝึกล้มเหลว",
            "prepare_short" to "เงียบ",
            "calibration_short" to "ปรับ",
            "done_short" to "เสร็จ",
            "error_short" to "ผิด",
            "retry_short" to "ลองใหม่",
            "retry_calibration" to "ปรับเทียบใหม่",
            "save" to "บันทึก",
            "cancel" to "ยกเลิก",
            "language" to "ภาษาแอป",
            "sensitivity" to "ความไว",
            "sensitivity_helper" to "ช่วง 0-100 ค่าเริ่มต้น 50",
            "total_hits" to "จำนวนครั้งทั้งหมด",
            "average_frequency" to "ความถี่เฉลี่ย",
            "hits_per_second" to "ครั้ง/วินาที",
            "best_burst" to "ช่วง 3 วินาทีที่ดีที่สุด",
            "burst_start" to "เริ่มช่วงระเบิด",
            "hits" to "ครั้ง",
            "activation_title" to "เปิดใช้งานอุปกรณ์",
            "activation_subtitle" to "กรอกซีเรียล 11 หลัก และรหัสเปิดใช้งาน 8 หลัก",
            "activation_hint" to "ต้องเปิดใช้งานก่อนเริ่มฝึก",
            "activation_required" to "แอปนี้ยังไม่ได้เปิดใช้งาน",
            "activation_loading" to "กำลังตรวจสอบซีเรียลและรหัส...",
            "activation_success" to "เปิดใช้งานสำเร็จ",
            "activation_failed" to "เปิดใช้งานไม่สำเร็จ",
            "activation_serial_not_found" to "ไม่พบหมายเลขซีเรียล",
            "activation_invalid_code" to "รหัสเปิดใช้งานไม่ถูกต้อง",
            "activation_already_bound" to "ซีเรียลนี้ถูกเปิดใช้งานบนอุปกรณ์อื่นแล้ว",
            "activation_not_activated" to "อุปกรณ์นี้ยังไม่ถูกเปิดใช้งาน",
            "activation_network_error" to "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ยืนยันได้",
            "serial_hint" to "ซีเรียล 11 หลัก",
            "code_hint" to "รหัสเปิดใช้งาน 8 หลัก",
            "serial_invalid" to "กรุณากรอกซีเรียล 11 หลักให้ถูกต้อง",
            "code_invalid" to "กรุณากรอกรหัส 8 หลักให้ถูกต้อง",
            "activate" to "เปิดใช้งาน",
            "lock_short" to "LOCK",
            "profile_title" to "โปรไฟล์",
            "profile_edit" to "แก้ไขโปรไฟล์",
            "profile_avatar" to "อวตาร",
            "profile_nickname" to "ชื่อเล่น",
            "profile_country" to "รหัสภูมิภาค",
            "profile_language" to "ภาษา",
            "profile_saved" to "อัปเดตโปรไฟล์แล้ว",
            "profile_save_failed" to "บันทึกโปรไฟล์ไม่สำเร็จ",
            "profile_empty" to "โปรไฟล์บนคลาวด์ยังไม่พร้อม",
            "cloud_refresh" to "รีเฟรชคลาวด์",
            "cloud_sync_loading" to "กำลังซิงก์ข้อมูลคลาวด์...",
            "cloud_sync_ready" to "ข้อมูลคลาวด์อัปเดตแล้ว",
            "cloud_sync_network" to "บริการคลาวด์ไม่พร้อมใช้งาน",
            "cloud_sync_idle" to "รอการซิงก์ครั้งถัดไป",
            "history_title" to "ประวัติการฝึก",
            "no_history" to "ยังไม่มีประวัติการฝึก",
            "leaderboard_title" to "อันดับ",
            "leaderboard_refresh" to "รีเฟรชอันดับ",
            "leaderboard_loading" to "กำลังโหลดอันดับ...",
            "leaderboard_ready" to "อัปเดตอันดับแล้ว",
            "leaderboard_empty" to "ยังไม่มีข้อมูลอันดับ",
            "leaderboard_me" to "อันดับของฉัน",
            "leaderboard_no_rank" to "คุณยังไม่ติดอันดับ",
            "total_sessions" to "จำนวนครั้งที่ฝึก",
            "best_30_hits" to "สถิติสูงสุด 30 วินาที",
            "best_60_hits" to "สถิติสูงสุด 60 วินาที",
            "cd_avatar_swatch" to "สีอวตาร %d",
        )
}


